author: Lynn Chen
lang: en
timezone: Asia/Shanghai
#theme_mode: [light|dark]
#theme_mode: dual
avatar: /assets/img/sample/avatar.png
title: Blingblogs
tagline: more than codes
description: >-
  A site with blogs involve backend, big data, or other daily programming records.
url: 'https://sechenbling.github.io'
baseurl: ''

github:
  username: sechenbling
twitter:
  username: sechenbling
bilibili:
  username: 15164783

social:
  name: Lynn Chen
  email: sechenblingbling@gmail.com
  links:
    - https://twitter.com/sechenbling
    - https://github.com/sechenbling
    - https://www.facebook.com/sechenbling
    - https://space.bilibili.com/15164783

google_site_verification: google_meta_tag_verification

#--------------------------

pwa:
  enabled: false

google_analytics:
  id: ''
  pv:
    enabled: false
    proxy_url: ''
    proxy_endpoint: ''
    cache: false

disqus:
  comments: false
  shortname: ''

# boolean type, the global switch for ToC in posts.
toc: true
paginate: 5
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

comments:
  active:         # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname:    # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo:         # <gh-username>/<repo>
    issue_term:   # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo:              # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping:           # optional, default to 'pathname'
    input_position:    # optional, default to 'bottom'
    lang:              # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# DO NOT change this unless you're a Pro user on Jekyll and Web development,
# or you think you're smart enough to change other relevant URLs within this template.

defaults:
  - scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true
      permalink: /posts/:title/
      toc: true
      breadcrumb:
        -
          label: Posts
          url: /
  -
    scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: index.html
    values:
      breadcrumb:
        -
          label: Posts
  - scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  sass_dir: _sass
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - vendor
  - Gemfile.lock
  - Gemfile
  - tools
  - docs
  - README.md
  - LICENSE
  - '*.gem'
  - '*.gemspec'

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: '/tags/:name/'
    category: '/categories/:name/'